### ISSUE TITLE
Add additional acceptable video extensions (.mp4, .mov, .avi)

### ISSUE THREAD

**Issue by hcwinsemius** [TAHMO/OpenRiverCam#29]
Currently, .mkv files are accepted in front end, other file formats not yet. See respons below.

![image](https://user-images.githubusercontent.com/7658673/110477741-d2f2ef80-80e3-11eb-9f4b-0bd2789a13a7.png)

**Comment by RickHagenaars** [comment]
mpeg was also supported and mp4 is added in commit https://github.com/TAHMO/OpenRiverCam/pull/33/commits/3c307a8188e20741757528d0f46ded6900f8d4f0
