### ISSUE TITLE
Extraction of cross-section velocities fails when latest bathymetry does not have any points

### ISSUE THREAD

**Issue by hcwinsemius** [TAHMO/OpenRiverCam#67]
Check needed that a minimal amount of points is needed on the bathymetry. I propose at least 6 to constrain the cross section, this would be sufficient for a concrete small channel for instance.

**Comment by RickHagenaars** [comment]
Besides checking the amount of bathymetry coordinate on the edit page of a bathymetry, we also need to put this in when we select a bathymetry to be used for movie processing.

Currently we just selected the most recent bathymetry for the site, but we'll need to put in a filter here that this most recent bathymetery should have 6 bathymetry coordinates at least.
